// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "89e751b8-bbab-4964-b592-9e3054bb89e9");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1650127536);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1650127535);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{de9f6e86-fa0b-409e-b2aa-84a3a64793ce}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1650127533);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b1493a4d-4774-470a-ac84-eb1b86ff31b8}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1650127535);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1650127537160");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1650149137160");
user_pref("browser.search.region", "KR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1650127535");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220202182137");
user_pref("browser.startup.homepage_override.mstone", "97.0");
user_pref("browser.startup.lastColdStartupCheck", 1650127534);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1650127535384");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "97.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "KR");
user_pref("dom.push.userAgentID", "4f074ab08d354ee89a5b20b88f82cd24");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220202182137");
user_pref("extensions.lastAppVersion", "97.0");
user_pref("extensions.lastPlatformVersion", "97.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0c56dc9d-7bc4-4879-8386-c92f35ec284e\",\"formautofill@mozilla.org\":\"b26bfec6-bf4d-4f9d-8dc8-56b42349297c\",\"pictureinpicture@mozilla.org\":\"14fe0383-8e28-4e9a-a2ac-11797dfaf96f\",\"screenshots@mozilla.org\":\"9966eff7-6531-48b1-ae3c-85ff69042c0b\",\"webcompat-reporter@mozilla.org\":\"9ab928a0-5d95-4420-b2d3-441c8b7c735f\",\"webcompat@mozilla.org\":\"efaecad4-03e9-4dc8-b53d-515f92fcb07d\",\"default-theme@mozilla.org\":\"52c6ecc7-c113-413f-bbbb-3a62c2c57267\",\"addons-search-detection@mozilla.com\":\"7227a231-f09e-4c9f-bd96-f234c1050afe\",\"google@search.mozilla.org\":\"2559972e-77f1-45c3-b5ca-058b04b5e3b3\",\"amazondotcom@search.mozilla.org\":\"853369f9-28bd-41cf-b61b-42cba0e1027f\",\"wikipedia@search.mozilla.org\":\"c79ec516-6b2b-44fc-8d04-b4aff2f22e75\",\"bing@search.mozilla.org\":\"36bd97d9-7f4c-403e-8989-bf4437ca7efe\",\"ddg@search.mozilla.org\":\"52001dd3-6ee9-45a7-85f3-a393b6f32232\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1650127535);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4190be71-6e97-4ced-a459-81f597f3e6e8");
user_pref("toolkit.startup.last_success", 1650127532);
user_pref("toolkit.telemetry.cachedClientID", "d556df4a-e55f-4154-9299-715463c025e1");
user_pref("toolkit.telemetry.previousBuildID", "20220202182137");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
